apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- deployment.yaml
- ingress.yaml
images:
- name: ghcr.io/impit-mpit//news-service-master
  newTag: fc4f514
- name: ghcr.io/impit-mpit/news-service-master
  newTag: latest
